services:
  api:
    build: .
    container_name: world_api_app
    ports:
      - "8080:8080"
    environment:
      # Aquí pondremos la IP de tu servidor y el puerto donde ya corre tu MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.18.36:3306/world?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: devpassword
      # IMPORTANTE: En producción usamos 'none' o 'validate', nunca 'update' para no romper tu BD
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate